version: '3.5'
services:
  app:
    build: flask_app
    command: gunicorn wsgi:app --bind 0.0.0:5000
    ports:
    - 5000:5000
  nginx:
    build: nginx
    ports:
    - 1337:80
    depends_on:
      - app
